In [1]:
# DATA ENGINEERING

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../data/raw/sensor_data.csv')
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   UDI                      10000 non-null  int64
 1   Product ID               10000 non-null  object
 2   Type                     10000 non-null  object
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64
 8   Machine failure          10000 non-null  int64
 9   TWF                      10000 non-null  int64
 10  HDF                      10000 non-null  int64
 11  PWF                      10000 non-null  int64
 12  OSF                      10000 non-null  int64
 13  RNF                      10000 non-null  int64
dtypes: float64(3), int64(9), object(2)
memory usage: 1.1+ MB

In [5]:
df.describe()

,UDI,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,5000.50000,300.004930,310.005560,1538.776100,39.986910,107.951000,0.033900,0.004600,0.011500,0.009500,0.009800,0.00190
std,2886.89568,2.000259,1.483734,179.284096,9.968934,63.654147,0.180981,0.067671,0.106625,0.097009,0.098514,0.04355
min,1.00000,295.300000,305.700000,1168.000000,3.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,2500.75000,298.300000,308.800000,1423.000000,33.200000,53.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
50%,5000.50000,300.100000,310.100000,1503.000000,40.100000,108.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
75%,7500.25000,301.500000,311.100000,1612.000000,46.800000,162.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
max,10000.00000,304.500000,313.800000,2886.000000,76.600000,253.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000

In [6]:
df.isnull().sum()

UDI                        0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
dtype: int64

In [7]:
print(df.shape)
print('-'*100)
print(df.ndim)
print('-'*100)
print(df.values)
print('-'*100)
print(df.columns)
print('-'*100)
print(df.index)

(10000, 14)
----------------------------------------------------------------------------------------------------
2
----------------------------------------------------------------------------------------------------
[[1 'M14860' 'M' ... 0 0 0]
 [2 'L47181' 'L' ... 0 0 0]
 [3 'L47182' 'L' ... 0 0 0]
 ...
 [9998 'M24857' 'M' ... 0 0 0]
 [9999 'H39412' 'H' ... 0 0 0]
 [10000 'M24859' 'M' ... 0 0 0]]
----------------------------------------------------------------------------------------------------
Index(['UDI', 'Product ID', 'Type', 'Air temperature [K]',
       'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]',
       'Tool wear [min]', 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF',
       'RNF'],
      dtype='object')
----------------------------------------------------------------------------------------------------
RangeIndex(start=0, stop=10000, step=1)

In [8]:
for i in df.columns:
    print(df[i].unique(),':-',i)
    print('-'*100)
    print(df[i].value_counts(),':-',i)
    print('-'*100)

[    1     2     3 ...  9998  9999 10000] :- UDI
----------------------------------------------------------------------------------------------------
UDI
1        1
6671     1
6664     1
6665     1
6666     1
        ..
3334     1
3335     1
3336     1
3337     1
10000    1
Name: count, Length: 10000, dtype: int64 :- UDI
----------------------------------------------------------------------------------------------------
['M14860' 'L47181' 'L47182' ... 'M24857' 'H39412' 'M24859'] :- Product ID
----------------------------------------------------------------------------------------------------
Product ID
M14860    1
L53850    1
L53843    1
L53844    1
L53845    1
         ..
M18193    1
M18194    1
L50515    1
L50516    1
M24859    1
Name: count, Length: 10000, dtype: int64 :- Product ID
----------------------------------------------------------------------------------------------------
['M' 'L' 'H'] :- Type
----------------------------------------------------------------------------------------------------
Type
L    6000
M    2997
H    1003
Name: count, dtype: int64 :- Type
----------------------------------------------------------------------------------------------------
[298.1 298.2 298.3 298.5 298.4 298.6 298.7 298.8 298.9 299.  299.1 298.
 297.9 297.8 297.7 297.6 297.5 297.4 297.3 297.2 297.1 297.  296.9 296.8
 296.7 296.6 296.5 296.3 296.4 296.2 296.1 296.  295.9 295.8 295.7 295.6
 295.5 295.4 295.3 299.2 299.3 299.5 299.4 299.6 299.7 299.8 299.9 300.
 300.1 300.2 300.3 300.4 300.5 300.6 300.7 300.8 300.9 301.  301.1 301.2
 301.3 301.4 301.5 301.6 301.7 301.8 301.9 302.  302.1 302.2 302.3 302.4
 302.5 302.6 302.7 302.8 302.9 303.  303.1 303.2 303.3 303.4 303.5 303.6
 303.7 303.8 303.9 304.  304.1 304.2 304.3 304.4 304.5] :- Air temperature [K]
----------------------------------------------------------------------------------------------------
Air temperature [K]
300.7    279
298.9    231
297.4    230
300.5    229
298.8    227
        ...
304.4      7
296.0      6
295.4      3
295.3      3
304.5      1
Name: count, Length: 93, dtype: int64 :- Air temperature [K]
----------------------------------------------------------------------------------------------------
[308.6 308.7 308.5 309.  308.9 309.1 309.2 309.3 309.4 309.5 308.8 308.4
 308.3 308.2 308.1 308.  307.9 309.6 309.7 309.8 309.9 310.  310.1 310.2
 307.8 307.7 307.6 307.5 307.4 307.3 307.2 307.1 307.  306.9 306.8 306.7
 306.6 306.5 306.4 306.3 306.2 306.1 306.  305.9 305.8 305.7 310.3 310.4
 310.5 310.6 310.7 310.8 310.9 311.  311.1 311.2 311.3 311.4 311.5 311.6
 311.7 311.8 311.9 312.  312.1 312.2 312.3 312.4 312.5 312.6 312.7 312.8
 313.  313.1 312.9 313.2 313.3 313.4 313.5 313.6 313.8 313.7] :- Process temperature [K]
----------------------------------------------------------------------------------------------------
Process temperature [K]
310.6    317
310.8    273
310.7    266
308.6    265
310.5    263
        ...
306.9      4
313.7      4
305.8      3
305.7      2
313.8      2
Name: count, Length: 82, dtype: int64 :- Process temperature [K]
----------------------------------------------------------------------------------------------------
[1551 1408 1498 1433 1425 1558 1527 1667 1741 1782 1423 1339 1742 2035
 1542 1311 1410 1306 1632 1375 1450 1581 1758 1561 1861 1512 1811 1439
 1693 1798 1419 1665 1559 1452 1379 1350 1362 1368 1372 1472 1489 1843
 1418 1412 2861 1383 1497 1565 1691 1477 1513 1661 1378 1393 1592 1829
 1812 1523 1394 1679 1466 1924 1369 1601 1461 1455 1398 1402 1445 1453
 1469 1422 1804 1436 1544 1487 1753 1830 1727 1622 1351 1575 1750 1529
 1852 1991 1555 1441 1591 1621 1572 1872 1499 1486 1680 1431 1564 1599
 1707 1467 1310 1546 1560 1329 1413 1587 1473 1737 1430 1711 1420 1297
 1449 1268 1511 1778 1407 1391 1612 1515 1463 1584 1850 1528 1987 1495
 1478 1471 1282 1586 1468 1440 1733 1458 1318 1610 1462 1382 1618 1988
 1304 1475 1824 1342 1485 1446 1301 1606 1539 1666 1678 2678 1432 1588
 1609 1636 1490 1344 1421 1386 1589 1548 1664 1447 1434 1416 1827 1569
 1629 1538 1570 1424 1552 1611 1777 1348 1442 1395 1627 1585 1405 1662
 1620 1357 1514 1331 1615 1482 1522 1654 1736 1390 1454 1954 1800 1524
 1520 1484 1426 1652 1401 1479 1819 1456 1626 2051 1568 1805 1385 1438
 1335 1392 1716 1713 2129 1567 1740 1374 1579 1305 1526 1313 1300 1646
 1714 1685 1550 1518 1448 1488 1699 1501 1373 1703 1720 1647 1749 1995
 1563 1474 1530 1388 2448 1459 1617 1595 1400 1507 1674 1658 1623 1517
 1521 1596 1640 1353 1604 1533 1754 2564 1842 1712 1414 1319 1249 1460
 1491 1571 1774 1502 2100 1722 1273 1600 1429 1573 2151 1657 1333 1496
 1208 1848 1493 1504 1341 1535 1389 1399 1582 1793 1376 1643 1510 1276
 1476 2874 2182 1619 1380 1833 1323 1583 1556 1324 1347 1404 1470 1326
 1505 1464 1543 1893 1415 1428 1715 1732 2027 1553 1709 1549 1443 1675
 1365 1759 1516 1775 1296 1803 1831 1958 1809 1332 1437 1698 1274 1650
 1503 1574 1669 1541 1935 1676 1700 1697 2001 1628 1525 1668 1312 1278
 1330 1480 1616 1547 2194 2000 1336 1403 1534 1634 1642 1686 1725 1926
 1509 1545 1554 1858 1536 1226 1608 2015 1683 1435 1562 1427 1729 1738
 1822 1577 1295 1656 1874 1531 1735 1354 1815 1838 1696 1500 1557 1506
 1361 1451 1289 1356 1978 1483 1492 1537 1286 1337 1343 1580 1409 1743
 1641 1605 2010 1828 1882 1285 1867 1338 1481 1566 1631 1465 1406 2833
 1444 1898 1951 1645 2044 1594 1358 1325 1892 1915 1235 1739 1397 2161
 1651 1370 1256 2270 1593 1396 1949 1363 1597 1263 1823 1287 1911 1387
 1508 1532 1644 1917 1655 1748 1638 2119 1168 2071 1633 1637 1291 1881
 1760 1648 1684 1607 1671 1927 1718 1840 1345 1653 1731 2008 2721 1695
 1540 1734 1292 1790 2077 1340 1258 1706 1672 1690 1271 1635 1846 1834
 1316 1367 1355 1352 1578 1417 1794 1776 1979 1371 2540 1359 1694 1702
 1763 1880 1364 2440 1726 1309 1280 1885 2243 2153 1868 1322 2098 1929
 1243 1411 1814 1719 1663 1771 1613 1721 1328 1717 1598 1334 1681 1708
 1366 1786 1603 2737 1494 1944 2083 1320 1377 1602 1677 1315 1519 1692
 2056 1976 1723 2206 2101 1614 2449 1787 1757 2304 1349 1781 2216 2090
 1230 2057 1639 1688 1877 1802 1590 1844 1921 1303 1761 1769 1384 1792
 1764 1952 2029 1457 1906 1948 1260 1624 2381 1576 1942 1950 1981 2886
 1847 2567 1767 2066 1784 1859 1327 1855 1752 1630 1242 1705 1902 1968
 1687 1977 1314 1969 1704 1791 1839 1266 1308 1281 1202 1298 1747 1785
 1279 1381 1660 1360 1940 1321 1701 2280 1941 1863 1762 1908 1939 1816
 1245 1965 2549 1821 1746 1886 1755 1744 1841 1772 1845 1856 1689 2384
 2022 1267 2329 1946 2069 1730 1766 1972 1795 1293 2248 2250 1957 2421
 1207 1670 1283 1346 1254 1294 1779 1751 2256 1728 1625 1869 2266 1302
 1851 1299 1889 1925 2183 1887 1875 1807 1997 1682 2496 1251 1888 1255
 1810 2355 1996 2007 1290 1659 1934 2174 1783 1932 2293 2141 2563 1780
 1649 2179 2025 1724 1288 1984 2068 1269 1937 1217 2289 1962 2432 1673
 2760 1989 2012 2297 1918 2639 1270 2092 1871 1980 1899 1317 1799 2672
 1192 1947 2465 1866 1928 1873 1916 1891 1227 2034 2709 1773 1903 2041
 1953 1985 1909 1931 2143 2691 2305 1865 2197 1895 1884 1765 1212 1832
 2211 1710 2157 2203 1905 1284 2032 2372 2825 2695 1259 2009 2676 2224
 2016 1923 1967 1307 1900 1275 2102 1820 1238 1854 1879 1817 1222 1959
 2133 2663 1818 2268 1756 1806 1922 2168 2232 1919 2344 1768 1789 2497
 2659 1825 2113 2245 1883 2643 2028 1901 2354 2117 1897 2130 2116 2706
 1262 2030 2024 1826 2023 2052 1745 1257 2370 2080 2170 1265 1907 2323
 2076 2055 1234 1894 1920 2156 1853 2003 2235 2047 1813 1228 2089 1236
 1975 1910 2165 2204 2021 1233 1248 1994 2065 1183 1913 2595 1770 1961
 1966 2103 1876 2093 1998 2137 2219 2636 1836 2207 2237 1801 2073 1878
 2377 2437 2478 2633 2127 2006 1960 2514 2288 1788 1261 2158 2424 1808
 1983 2084 1864 2261 1999 2579 2013 2074 2026 1936 1246 2097 1964 2072
 1272 1200 2218 2142 2140 1264 2710 2004 1835 2144 1229 1796 2099 2240
 1225 2617 1971 1181 1870 2011 2262 2267 2188 1797 1896 2358 1970 2456
 2042 1904 1862 2186 2033 2189 1837 2136 1890 2109 2049 2053 2231 2271
 2118 2312 2450] :- Rotational speed [rpm]
----------------------------------------------------------------------------------------------------
Rotational speed [rpm]
1452    48
1435    43
1447    42
1429    40
1469    40
        ..
2197     1
2211     1
1905     1
1893     1
2450     1
Name: count, Length: 941, dtype: int64 :- Rotational speed [rpm]
----------------------------------------------------------------------------------------------------
[42.8 46.3 49.4 39.5 40.  41.9 42.4 40.2 28.6 28.  23.9 44.3 51.1 30.
 19.6 48.4 46.6 45.6 54.5 32.5 42.7 44.8 30.7 25.7 37.3 23.3 39.  24.6
 44.2 30.1 48.2 25.5 48.3 34.7 48.6 36.7 39.2 50.7 52.5 45.4 50.8 49.1
 48.5 47.5 25.8 53.9 44.1  4.6 54.9 43.8 35.1 40.7 40.3 29.5 54.4 52.6
 38.2 22.9 25.9 38.6 45.1 28.7 32.4 65.7 22.6 45.5 44.4 35.  32.3 46.7
 47.9 41.3 51.5 37.9 49.9 40.8 40.1 47.6 26.8 43.9 31.8 45.2 24.9 27.1
 43.  31.9 52.2 35.3 29.9 32.7 25.  20.7 40.6 40.5 43.4 31.1 46.8 34.1
 22.5 43.5 29.4 45.7 33.  28.1 44.7 41.2 32.2 60.5 46.5 34.3 41.1 27.7
 43.2 49.6 53.  28.5 55.3 55.8 36.1 35.2 28.2 50.5 33.6 48.  39.9 37.6
 41.  27.  36.2 19.8 46.  47.  60.7 52.3 35.5 43.6 26.  32.6 42.9 62.3
 59.1 20.8 33.7 58.3 21.4 50.2 49.8 24.2 48.1 30.6 56.  43.1 34.6 51.8
 10.7 49.5 40.9 47.1 35.7 32.8 44.  33.9 52.9 44.9 37.1 38.3 31.6 38.1
 46.2 52.7 24.3 45.  34.4 29.3 53.8 49.2 34.8 34.9 38.7 36.6 50.3 51.6
 58.8 31.4 33.5 56.8 56.2 42.6 35.8 40.4 63.  63.9 32.1 43.7 21.1 24.8
 37.  39.6 54.7 26.6 23.4 36.5 19.2 36.  33.2 42.2 25.3 18.7 35.6 27.5
 47.2 41.8 28.4 27.8 41.4 56.7 51.9 31.3 20.5 39.4 13.8 32.9 31.7 31.
 36.9 48.9 34.2 36.8 30.9 47.8 55.2 57.5 37.2 51.7 42.  37.4 12.8 50.9
 60.4 54.8 37.7 28.9 49.7 16.9 30.4 59.8 45.9 57.6 42.1 34.5 37.8 50.1
 17.7 39.7 23.7 36.3 38.5 61.5 26.7 59.9 41.7 46.1 57.4 53.6 42.3  4.2
 41.5 16.5 57.3 32.  56.9 35.9 38.8 30.2 27.4 43.3 37.5 58.2 20.6 35.4
 50.6 29.8 33.4 52.4 24.7 22.1 39.3 53.2 54.3 45.3 29.  49.  55.4 33.1
 27.9 50.4 53.1 16.8 21.3 71.6 33.8 47.7 29.1 57.8 41.6 51.3 58.7 28.8
 38.9 44.5 20.1 58.6 47.4 24.  25.4 61.2 47.3 48.8 24.4 29.7 26.4 55.6
 50.  27.3 46.4 45.8 58.1 23.8 44.6 54.6 46.9 62.  22.3 48.7 56.5 51.
 30.8 33.3 18.9 52.1 22.8 52.   5.6 22.7 53.3 21.7 22.4 76.2 42.5 31.2
 14.6 27.6 21.9 61.8 20.9 26.2 21.  39.1 18.3 63.4 19.4 29.6 53.4 68.3
 57.7 34.  38.  19.1 25.1 52.8 30.5 36.4 25.2 39.8 56.4 17.5  9.3 69.
 51.4 61.4 69.1 25.6 58.  57.1 30.3 20.4 55.9 53.5 13.3 59.  23.5 14.
 15.7 65.9 15.3 57.  74.5 27.2 31.5 26.1  8.8 62.7 18.2 54.  49.3 29.2
 61.9 28.3 60.2 19.3 58.5 69.4 16.3 17.4 55.7 15.1 55.5 19.  59.6 18.
 61.  51.2 62.9 59.5 57.9 59.3 26.3 21.6 19.9 54.2 14.2 60.1 20.3 23.2
  3.8 67.3 23.6 56.3 23.  62.8 21.5 58.4 54.1 20.2 57.2 55.1 18.4 67.
 59.7 66.3 60.  15.4 38.4 60.3 64.  13.  60.6 56.1 60.9 55.  15.  20.
 63.6 68.2 26.5 53.7 16.6 67.5 66.5 62.1 61.3 15.9 64.8 65.1 17.8 62.2
 63.2 13.5 14.4 19.7 24.5 72.8 21.8 22.  17.9 63.1 62.4 56.6 16.4 62.6
  8.  65.3 15.8 12.  18.6 11.8 68.9 13.7 23.1 26.9 67.6  9.7 62.5 18.8
 66.7 59.2 17.3 12.1 16.1 68.6 59.4 68.  13.9  5.8 12.6 65.5 66.8 10.8
 17.2 21.2 16.  67.8 17.  11.4 58.9 70.6 15.2 17.6 61.1 12.7 64.4 18.1
 16.7  9.8 63.8 70.5 68.5 71.3 14.7 70.  18.5 66.4 67.9 64.6 64.9 24.1
 66.1 73.6 63.7 60.8 65.8 65.6 12.2 63.5 67.2 22.2 14.3 13.4 64.7 61.7
 14.5 69.6 14.9 12.5 65.2 71.8 76.6 64.2 69.7 61.6 64.1 72.  75.4 15.6
 19.5 16.2 15.5] :- Torque [Nm]
----------------------------------------------------------------------------------------------------
Torque [Nm]
40.2    52
38.5    50
42.4    50
35.8    50
37.7    49
        ..
65.7     1
67.8     1
16.0     1
4.6      1
15.5     1
Name: count, Length: 577, dtype: int64 :- Torque [Nm]
----------------------------------------------------------------------------------------------------
[  0   3   5   7   9  11  14  16  18  21  24  29  34  37  40  42  44  47
  50  55  58  63  65  68  70  73  75  77  82  84  86  89  91  93  95  98
 101 104 106 111 113 115 117 120 125 128 130 133 135 140 143 145 147 152
 154 156 158 160 162 165 167 169 172 174 177 179 181 184 189 191 193 196
 198 200 202 204 206 208   2   4  13  15  17  20  25  27  30  33  35  53
  57  59  61  66  72  80  92  97  99 103 108 110 112 114 116 118 122 124
 126 132 138 148 150 155 157 159 161 164 186 188 194 203 211 214 216 218
   8  10  22  32  39  41  43  45  49  54  67  69  74  76  81  96 105 107
 119 137 142 144 146 151 153 166 168 170 173 175 183 185 190 195 197 209
 212  19  51  56  78  83  85  88  90  94 109 131 134 136 192 199 201 205
 210 215  48  71  79 123 127 129 141 176 178 180 182 207 213  28 139 163
 171 221   6  26  46  60 100 121 220 222 224 229 231 233 235 240  31  38
 187  12  23  62  64  87 217 219 227 236 238 102 149  36 223 226 228 230
 225  52 242 244 246 232 234 237 239 241 251 253] :- Tool wear [min]
----------------------------------------------------------------------------------------------------
Tool wear [min]
0      120
2       69
5       63
7       58
59      58
      ...
237      1
239      1
241      1
251      1
253      1
Name: count, Length: 246, dtype: int64 :- Tool wear [min]
----------------------------------------------------------------------------------------------------
[0 1] :- Machine failure
----------------------------------------------------------------------------------------------------
Machine failure
0    9661
1     339
Name: count, dtype: int64 :- Machine failure
----------------------------------------------------------------------------------------------------
[0 1] :- TWF
----------------------------------------------------------------------------------------------------
TWF
0    9954
1      46
Name: count, dtype: int64 :- TWF
----------------------------------------------------------------------------------------------------
[0 1] :- HDF
----------------------------------------------------------------------------------------------------
HDF
0    9885
1     115
Name: count, dtype: int64 :- HDF
----------------------------------------------------------------------------------------------------
[0 1] :- PWF
----------------------------------------------------------------------------------------------------
PWF
0    9905
1      95
Name: count, dtype: int64 :- PWF
----------------------------------------------------------------------------------------------------
[0 1] :- OSF
----------------------------------------------------------------------------------------------------
OSF
0    9902
1      98
Name: count, dtype: int64 :- OSF
----------------------------------------------------------------------------------------------------
[0 1] :- RNF
----------------------------------------------------------------------------------------------------
RNF
0    9981
1      19
Name: count, dtype: int64 :- RNF
----------------------------------------------------------------------------------------------------

In [9]:
# adding timestamp
df['timestamp'] = pd.date_range(start='2024-01-01',periods=len(df),freq='min')

In [10]:
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF,timestamp
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0,2024-01-01 00:00:00
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0,2024-01-01 00:01:00
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0,2024-01-01 00:02:00
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0,2024-01-01 00:03:00
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0,2024-01-01 00:04:00

In [11]:
df = df.sort_values(by='timestamp')

In [12]:
df = df.ffill()

In [13]:
df.drop(['UDI','Product ID'],axis=1 , inplace=True)

In [14]:
df.head()

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF,timestamp
0,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0,2024-01-01 00:00:00
1,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0,2024-01-01 00:01:00
2,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0,2024-01-01 00:02:00
3,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0,2024-01-01 00:03:00
4,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0,2024-01-01 00:04:00

In [15]:
df = pd.get_dummies(df,columns=['Type'],drop_first=True)

In [16]:
df['Type_L'] = df['Type_L'].astype(int)

In [17]:
df['Type_M'] = df['Type_M'].astype(int)

In [18]:
df.to_csv('../data/processed/cleaned.csv',index=False)

In [19]:
# verifying
df_check = pd.read_csv('../data/processed/cleaned.csv')
df_check.head()

,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF,timestamp,Type_L,Type_M
0,298.1,308.6,1551,42.8,0,0,0,0,0,0,0,2024-01-01 00:00:00,0,1
1,298.2,308.7,1408,46.3,3,0,0,0,0,0,0,2024-01-01 00:01:00,1,0
2,298.1,308.5,1498,49.4,5,0,0,0,0,0,0,2024-01-01 00:02:00,1,0
3,298.2,308.6,1433,39.5,7,0,0,0,0,0,0,2024-01-01 00:03:00,1,0
4,298.2,308.7,1408,40.0,9,0,0,0,0,0,0,2024-01-01 00:04:00,1,0

In [20]:
print(df.shape)
print(df_check.shape)

(10000, 14)
(10000, 14)

In [21]:
df_check.isnull().sum()

Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Machine failure            0
TWF                        0
HDF                        0
PWF                        0
OSF                        0
RNF                        0
timestamp                  0
Type_L                     0
Type_M                     0
dtype: int64

In [22]:
# loading cleaned data 
df = pd.read_csv('../data/processed/cleaned.csv')
df.head()

,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF,timestamp,Type_L,Type_M
0,298.1,308.6,1551,42.8,0,0,0,0,0,0,0,2024-01-01 00:00:00,0,1
1,298.2,308.7,1408,46.3,3,0,0,0,0,0,0,2024-01-01 00:01:00,1,0
2,298.1,308.5,1498,49.4,5,0,0,0,0,0,0,2024-01-01 00:02:00,1,0
3,298.2,308.6,1433,39.5,7,0,0,0,0,0,0,2024-01-01 00:03:00,1,0
4,298.2,308.7,1408,40.0,9,0,0,0,0,0,0,2024-01-01 00:04:00,1,0

In [23]:
df = df.sort_values(by='timestamp')

In [24]:
# rolling mean 
df['air_temp_mean_6'] = df['Air temperature [K]'].rolling(6).mean()

In [25]:
df['process_temp_mean_6'] = df['Process temperature [K]'].rolling(6).mean()

In [26]:
# rolling standard deviation 
df['rpm_std_6'] = df['Rotational speed [rpm]'].rolling(6).std()

In [27]:
df['torque_std_6'] = df['Torque [Nm]'].rolling(6).std()

In [28]:
df['air_temp_lag1'] = df['Air temperature [K]'].shift(1)

In [29]:
df['air_temp_lag2'] = df['Air temperature [K]'].shift(2)

In [30]:
df['temp_diff'] = df['Process temperature [K]'] - df['Air temperature [K]']

In [31]:
df['wear_torque'] = df['Tool wear [min]'] * df['Torque [Nm]']

In [32]:
df = df.dropna()

In [33]:
# saving
df.to_csv('../data/features/features.csv',index=False)

In [34]:
df.head()

,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,...,Type_L,Type_M,air_temp_mean_6,process_temp_mean_6,rpm_std_6,torque_std_6,air_temp_lag1,air_temp_lag2,temp_diff,wear_torque
5,298.1,308.6,1425,41.9,11,0,0,0,0,0,...,0,1,298.150000,308.616667,58.066915,3.840529,298.2,298.2,10.5,460.9
6,298.1,308.6,1558,42.4,14,0,0,0,0,0,...,1,0,298.150000,308.616667,60.431780,3.854737,298.1,298.2,10.5,593.6
7,298.1,308.6,1527,40.2,16,0,0,0,0,0,...,1,0,298.133333,308.600000,61.440757,3.690348,298.1,298.1,10.5,643.2
8,298.3,308.7,1667,28.6,18,0,0,0,0,0,...,0,1,298.166667,308.633333,100.504726,5.108685,298.1,298.1,10.4,514.8
9,298.5,309.0,1741,28.0,21,0,0,0,0,0,...,0,1,298.216667,308.700000,131.483332,6.690815,298.3,298.1,10.5,588.0

In [35]:
df.shape

(9995, 22)

In [37]:
df = pd.read_csv("../data/features/features.csv")

In [ ]:
# Renaming columns
df = df.rename(columns={
    "Air temperature [K]": "air_temp",
    "Process temperature [K]": "process_temp",
    "Rotational speed [rpm]": "rotational_speed",
    "Torque [Nm]": "torque",
    "Tool wear [min]": "tool_wear",
    "Machine failure": "machine_failure"
})

In [ ]:
#  Droping leakage and unnecessary columns
df = df.drop(columns=[
    "TWF", "HDF", "PWF", "OSF", "RNF", "timestamp"
], errors="ignore")

In [ ]:
# Saving cleaned version
df.to_csv("../data/features/features.csv", index=False)

print("Dataset cleaned")

Dataset cleaned

In [42]:
print(df.columns.tolist())

['air_temp', 'process_temp', 'rotational_speed', 'torque', 'tool_wear', 'machine_failure', 'Type_L', 'Type_M', 'air_temp_mean_6', 'process_temp_mean_6', 'rpm_std_6', 'torque_std_6', 'air_temp_lag1', 'air_temp_lag2', 'temp_diff', 'wear_torque']

In [ ]:
# ML ENGINEERING